language: nix

env:
  global:
    - LC_ALL=en_US.UTF-8
  matrix:
    - STACK_YAML=stack-lts-2.yaml
    - STACK_YAML=stack-lts-6.yaml
    - STACK_YAML=stack-lts-10.yaml
    - STACK_YAML=stack-nightly.yaml

cache:
  directories:
    - $HOME/.stack
    - /nix/store

before_install:
  - nix-env -i stack
  - stack upgrade

script:
  - stack test --nix --no-nix-pure --no-terminal --stack-yaml $STACK_YAML

notifications:
  email: false
