name: foo
version: 0.0.0.1
github: chris-martin/foo

synopsis: |
  ...

description: |
  ...

category: ...

author:     Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>

license: Apache-2.0
license-file: license.txt

ghc-options:
  - -Wall

library:
  source-dirs: src
  exposed-modules:
    - Foo

dependencies:
  - base

tests:

  doctest:
    source-dirs: test
    main: doctest.hs
    ghc-options:
      - -threaded
    dependencies:
      - doctest

  hedgehog:
    source-dirs: test
    main: hedgehog.hs
    ghc-options:
      - -threaded
    dependencies:
      - foo
      - hedgehog
